name: YouTube Auto-Comment Bot

on:
  schedule:
    # Run at 6 AM and 6 PM Eastern Time (UTC-4/UTC-5 depending on DST)
    # 11:00 UTC is 6 AM EST (when not in DST)
    # 10:00 UTC is 6 AM EDT (during DST)
    # 23:00 UTC is 6 PM EST (when not in DST)
    # 22:00 UTC is 6 PM EDT (during DST)
    - cron: '0 10,22 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run YouTube Bot
        run: python main.py --run-once
        env:
          # Add any environment variables the bot might need
          PYTHONUNBUFFERED: 1 
